// Shared career data — used by both the WhatsApp flow (api/webhook.js) and
// the PDF report generator (api/report.js).

const TRAIT_NAMES = {
  R: "Hands-on & practical",
  I: "Curious & analytical",
  A: "Creative & expressive",
  S: "Caring & people-focused",
  E: "Driven & enterprising",
  C: "Organised & detail-focused",
};

// traits[0] = primary, traits[1] = secondary (optional)
const CAREERS = [
  { id: "engineer", name: "Engineer (Civil/Mechanical/Electrical)", traits: ["R", "I"], list: "Design and build the physical world",
    why: "Engineering blends hands-on problem-solving with strong maths and science — a great fit for practical, analytical minds.",
    subjects: "Mathematics + Physical Sciences (NOT Maths Literacy).",
    qual: "A 4-year BEng/BSc(Eng) at university, or a National Diploma in Engineering at a TVET college / University of Technology. Strong Maths & Science marks are essential." },
  { id: "electrician", name: "Electrician", traits: ["R"], list: "Install and repair electrical systems",
    why: "It's hands-on, technical work that's in high demand and pays well — ideal if you like fixing things and seeing real results.",
    subjects: "Mathematics (or Technical Maths); Physical Sciences helps.",
    qual: "TVET college electrical courses (N1-N6) plus a learnership/apprenticeship, then a Trade Test to qualify as an artisan." },
  { id: "mechanic", name: "Motor Mechanic", traits: ["R"], list: "Diagnose and repair vehicles",
    why: "If you like working with your hands and understanding how machines work, this is a practical, always-in-demand trade.",
    subjects: "Mathematics / Technical Maths; Physical Sciences helpful.",
    qual: "TVET Motor Mechanics programme + apprenticeship + Trade Test." },
  { id: "doctor", name: "Doctor (Medicine)", traits: ["I", "S"], list: "Diagnose and treat patients",
    why: "Medicine suits curious, caring people who love science and want to help others directly.",
    subjects: "Mathematics + Physical Sciences + Life Sciences (high marks needed).",
    qual: "A 6-year MBChB degree at university. Very competitive - aim for excellent marks across Maths and Sciences." },
  { id: "datasci", name: "Data Scientist / IT Specialist", traits: ["I", "C"], list: "Find answers in data & build tech",
    why: "Strong analytical thinkers who enjoy maths and problem-solving thrive in data, software and tech roles.",
    subjects: "Mathematics is essential (NOT Maths Literacy).",
    qual: "A BSc in Computer Science / Data Science, or a National Diploma in IT at a University of Technology." },
  { id: "scientist", name: "Scientist / Researcher", traits: ["I"], list: "Investigate how the world works",
    why: "If you love understanding why and how things happen, research lets you explore science deeply.",
    subjects: "Mathematics + Physical Sciences and/or Life Sciences.",
    qual: "A BSc degree, usually followed by Honours and Masters for research roles." },
  { id: "designer", name: "Graphic / UX Designer", traits: ["A"], list: "Create visuals, brands and apps",
    why: "Creative, expressive people who like making things look good and work well are a natural fit for design.",
    subjects: "No strict requirements; Visual Arts or Design helps. Good marks in any subjects.",
    qual: "A Diploma or Degree in Graphic / Visual / UX Design at a university, UoT or design college. A strong portfolio matters most." },
  { id: "architect", name: "Architect", traits: ["A", "R"], list: "Design buildings and spaces",
    why: "Architecture combines creativity with structure and maths - perfect for imaginative but practical thinkers.",
    subjects: "Mathematics + Physical Sciences, plus creative/visual aptitude.",
    qual: "A BAS (Architectural Studies) degree, then Honours and a Master of Architecture, or an Architectural Technology diploma." },
  { id: "media", name: "Journalist / Media & Content", traits: ["A", "S"], list: "Tell stories across media",
    why: "If you love writing, ideas and communicating, media and content creation let you express and inform.",
    subjects: "Strong Languages; good marks in any subjects.",
    qual: "A Diploma or Degree in Journalism, Media Studies or Communications." },
  { id: "teacher", name: "Teacher", traits: ["S"], list: "Educate and shape young minds",
    why: "Patient, caring people who enjoy explaining things and helping others grow make great teachers.",
    subjects: "Languages plus the subjects you'd like to teach.",
    qual: "A 4-year BEd degree, or a Bachelor's degree followed by a PGCE. Funza Lushaka bursaries are often available." },
  { id: "nurse", name: "Nurse", traits: ["S", "I"], list: "Care for patients' health",
    why: "Nursing fits caring people who also enjoy health science and want hands-on impact.",
    subjects: "Life Sciences + Mathematics or Maths Literacy (varies by institution).",
    qual: "A 4-year Bachelor of Nursing, or a nursing diploma at an accredited college." },
  { id: "socialworker", name: "Social Worker", traits: ["S"], list: "Support people and communities",
    why: "If you want to make a real difference in people's lives, social work is deeply people-centred.",
    subjects: "Life Sciences or History helpful; good Languages.",
    qual: "A 4-year Bachelor of Social Work (BSW). Government bursaries are often available." },
  { id: "entrepreneur", name: "Entrepreneur / Business Owner", traits: ["E"], list: "Build and run your own business",
    why: "Ambitious, persuasive self-starters who like leading and taking risks suit entrepreneurship.",
    subjects: "No fixed subjects; Business Studies, Accounting & Maths help.",
    qual: "No degree is required, but a BCom or business diploma builds useful skills. Many start by learning and doing." },
  { id: "lawyer", name: "Lawyer", traits: ["E", "I"], list: "Advise, argue and uphold justice",
    why: "Confident, analytical people who enjoy reasoning and persuading thrive in law.",
    subjects: "Strong Languages; good marks in any subjects (Maths helps).",
    qual: "A 4-year LLB degree, then practical articles and admission as an attorney or advocate." },
  { id: "marketing", name: "Marketing & Sales", traits: ["E", "A"], list: "Promote products and win customers",
    why: "Outgoing, persuasive and creative people do well in marketing, sales and brand work.",
    subjects: "Business Studies helpful; good Languages.",
    qual: "A Diploma or Degree in Marketing, Business or Communications." },
  { id: "accountant", name: "Accountant / Chartered Accountant", traits: ["C", "I"], list: "Manage money, audits and finances",
    why: "Organised, detail-focused people who are good with numbers are well suited to accounting and finance.",
    subjects: "Mathematics (essential) + Accounting.",
    qual: "A BCom Accounting degree, then SAICA articles to qualify as a Chartered Accountant (CA)." },
  { id: "banker", name: "Banking & Finance", traits: ["C", "E"], list: "Work with money, markets and clients",
    why: "If you like numbers, structure and business, finance offers stable and varied careers.",
    subjects: "Mathematics + Accounting helpful.",
    qual: "A BCom in Finance/Economics, or a finance diploma at a UoT/college." },
  { id: "logistics", name: "Logistics & Supply Chain", traits: ["C", "E"], list: "Move goods and plan operations",
    why: "Organised planners who like efficiency and coordination suit logistics and operations.",
    subjects: "Mathematics or Maths Literacy; Business Studies helpful.",
    qual: "A Diploma or Degree in Logistics, Supply Chain or Operations Management." },
];

const careerById = (id) => CAREERS.find((c) => c.id === id);

module.exports = { TRAIT_NAMES, CAREERS, careerById };
