// Shared career data — used by both the WhatsApp flow (api/webhook.js) and
// the PDF report generator (api/report.js).
//
// 88 careers, counsellor-approved July 2026 (CAREER_RESEARCH_DRAFT.md).
// traits = high-point Holland code (1-3 letters), primary first. Matching uses
// lib/assessment.js affinity() — cosine of the person's six scores against a
// profile synthesized from this code. See docs/RIASEC_MATCHING_SPEC.md.
//
// FACTUAL fields (traits, subjects, qual, aiImpact) derive from the approved
// draft. `list`/`why` for the 72 new careers are auto-generated v1 copy
// (the 16 pre-existing careers keep their hand-written copy); a copy polish
// pass is worthwhile but nothing here is inaccurate.

const TRAIT_NAMES = {
  R: "Hands-on & practical",
  I: "Curious & analytical",
  A: "Creative & expressive",
  S: "Caring & people-focused",
  E: "Driven & enterprising",
  C: "Organised & detail-focused",
};

const CAREERS = [
  { id: "engineer", name: "Engineer (Civil/Mechanical/Electrical)", traits: ["R", "I"], list: "Design and build the physical world",
    why: "Engineering blends hands-on problem-solving with strong maths and science — a great fit for practical, analytical minds.",
    subjects: "Mathematics + Physical Sciences (NOT Maths Literacy).",
    qual: "A 4-year BEng/BSc(Eng) at university, or a National Diploma in Engineering at a TVET college / University of Technology. Strong Maths & Science marks are essential.",
    aiImpact: "Medium", aiImpactNote: "design, drafting, and simulation work increasingly AI-assisted, but WEF names green/renewable engineering roles among the fastest-*growing* occupations globally, and Pr Eng registration keeps legal/safety accountability with a licensed huma" },
  { id: "electrician", name: "Electrician", traits: ["R"], list: "Install and repair electrical systems",
    why: "It's hands-on, technical work that's in high demand and pays well — ideal if you like fixing things and seeing real results.",
    subjects: "Mathematics (or Technical Maths); Physical Sciences helps.",
    qual: "TVET college electrical courses (N1-N6) plus a learnership/apprenticeship, then a Trade Test to qualify as an artisan.",
    aiImpact: "Low", aiImpactNote: "hands-on physical trade; the Anthropic Economic Index finds skilled trades among the occupation categories with near-zero measured AI exposure." },
  { id: "mechanic", name: "Motor Mechanic", traits: ["R"], list: "Diagnose and repair vehicles",
    why: "If you like working with your hands and understanding how machines work, this is a practical, always-in-demand trade.",
    subjects: "Mathematics / Technical Maths; Physical Sciences helpful.",
    qual: "TVET Motor Mechanics programme + apprenticeship + Trade Test.",
    aiImpact: "Low", aiImpactNote: "physical diagnostic and repair work; diagnostic software already assists but doesn't replace hands-on repair." },
  { id: "plumber", name: "Plumber", traits: ["R"], list: "Practical, hands-on work",
    why: "Fits practical minds — work that rewards those strengths.",
    subjects: "Mathematics (Pure), Physical Sciences are the subjects that help most.",
    qual: "N1-N3 (CETA) + apprenticeship (3-4yr) ",
    aiImpact: "Low", aiImpactNote: "hands-on physical trade, same reasoning as Electrician/Motor Mechanic." },
  { id: "boilermaker", name: "Boilermaker", traits: ["R"], list: "Practical, hands-on work",
    why: "Fits practical minds — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, Engineering Graphics & Design are the subjects that help most.",
    qual: "3yr apprenticeship (structured %-split college/workplace) ",
    aiImpact: "Low", aiImpactNote: "hands-on physical trade." },
  { id: "welder", name: "Welder", traits: ["R"], list: "Practical, hands-on work",
    why: "Fits practical minds — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences are the subjects that help most.",
    qual: "N2/NCV/Technical Matric or Grade 9+4yr experience ",
    aiImpact: "Low", aiImpactNote: "hands-on physical trade; robotic welding exists in heavy manufacturing but doesn't displace the general trade." },
  { id: "diesel-mechanic", name: "Diesel Mechanic", traits: ["R"], list: "Practical, hands-on work",
    why: "Fits practical minds — work that rewards those strengths.",
    subjects: "Mathematics (Pure), Physical Sciences are the subjects that help most.",
    qual: "N1-N3/NCV + ~3yr apprenticeship ",
    aiImpact: "Low", aiImpactNote: "hands-on physical trade." },
  { id: "carpenter-joiner", name: "Carpenter/Joiner", traits: ["R"], list: "Practical, hands-on work",
    why: "Fits practical minds — work that rewards those strengths.",
    subjects: "Mathematics is the subject that helps most.",
    qual: "N2+ qualification + ~2.5yr on-the-job training ",
    aiImpact: "Low", aiImpactNote: "hands-on physical trade." },
  { id: "bricklayer", name: "Bricklayer", traits: ["R"], list: "Practical, hands-on work",
    why: "Fits practical minds — work that rewards those strengths.",
    subjects: "No fixed subject requirement — Mathematics and good language marks are a strong foundation.",
    qual: "merSETA/CETA learnership ",
    aiImpact: "Low", aiImpactNote: "hands-on physical trade." },
  { id: "commercial-pilot", name: "Commercial Pilot", traits: ["R", "I"], list: "Practical, hands-on, analytical work",
    why: "Fits practical minds with a analytical streak — work that rewards those strengths.",
    subjects: "Mathematics (Pure), Physical Sciences are the subjects that help most.",
    qual: "SACAA-approved flight school (PPL",
    aiImpact: "Low", aiImpactNote: "commercial aviation remains a certified-human-pilot industry with heavy safety regulation; autonomous-flight technology is a genuine but distant research horizon, not a near-term factor." },
  { id: "chef", name: "Chef", traits: ["R", "A"], list: "Practical, hands-on, creative work",
    why: "Fits practical minds with a creative streak — work that rewards those strengths.",
    subjects: "Mathematics, Maths Literacy, English are the subjects that help most.",
    qual: "1-3yr culinary diploma/certificate (Prue Leith, ICA Chef School, hotel schools) — vocational, aptitude/passion often weighted over academic marks",
    aiImpact: "Low", aiImpactNote: "physical, sensory craft; hospitality is one of the sectors the Anthropic Economic Index finds least AI-exposed." },
  { id: "agricultural-farm-manager", name: "Agricultural/Farm Manager", traits: ["R", "E"], list: "Practical, hands-on, enterprising work",
    why: "Fits practical minds with a enterprising streak — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, Life Sciences, Agricultural Sciences are the subjects that help most.",
    qual: "Agricultural College Diploma (Elsenburg, Cedara, Tsolo) 2-3yr for practical management",
    aiImpact: "Low", aiImpactNote: "fundamentally physical, land-based work; WEF projects large absolute *growth* in farming-related roles by 2030 (34 million additional, driven by the green transition), with AI/precision-agriculture tools acting as a support layer rather tha" },
  { id: "game-ranger-wildlife-manager", name: "Game Ranger/Wildlife Manager", traits: ["R", "I"], list: "Practical, hands-on, analytical work",
    why: "Fits practical minds with a analytical streak — work that rewards those strengths.",
    subjects: "Mathematics, Life Sciences, Geography are the subjects that help most.",
    qual: "(a) Field guide route: FGASA-accredited short courses (EcoTraining, Bushwise, SAWC) — fast, lower bar",
    aiImpact: "Low", aiImpactNote: "outdoor, physically-present, human-guiding role." },
  { id: "fitter-turner", name: "Fitter & Turner", traits: ["R"], list: "Practical, hands-on work",
    why: "Fits practical minds — work that rewards those strengths.",
    subjects: "No fixed subject requirement — Mathematics and good language marks are a strong foundation.",
    qual: "N1-N2/N3 (Fitting & Machining) + merSETA apprenticeship ",
    aiImpact: "Low", aiImpactNote: "hands-on physical trade." },
  { id: "refrigeration-technician", name: "Refrigeration Technician", traits: ["R"], list: "Practical, hands-on work",
    why: "Fits practical minds — work that rewards those strengths.",
    subjects: "English is the subject that helps most.",
    qual: "N-courses (Air Conditioning & Refrigeration) + merSETA apprenticeship ",
    aiImpact: "Low", aiImpactNote: "hands-on physical trade." },
  { id: "landscaper-landscape-technic", name: "Landscaper/Landscape Technician", traits: ["R", "A"], list: "Practical, hands-on, creative work",
    why: "Fits practical minds with a creative streak — work that rewards those strengths.",
    subjects: "Maths Literacy, Physical Sciences, Life Sciences, English are the subjects that help most.",
    qual: "Distinguish \"landscaper\" (hands-on trade, National Certificate: Landscaping) from \"Landscape Technologist\" (SACLAP-registered professional tier, needs NQF6 Diploma) from \"Landscape Architect\" (full professional degree)",
    aiImpact: "Low", aiImpactNote: "the hands-on landscaper trade tier is physical, outdoor work; the Landscape Architect design tier sees more AI-assisted design software use, but stays a small part of this career's overall population." },
  { id: "merchant-navy-marine-officer", name: "Merchant Navy/Marine Officer", traits: ["R", "I"], list: "Practical, hands-on, analytical work",
    why: "Fits practical minds with a analytical streak — work that rewards those strengths.",
    subjects: "Mathematics (Pure), Physical Sciences are the subjects that help most.",
    qual: "Grade 12 or N3 (60%+) ",
    aiImpact: "Low", aiImpactNote: "physically-present, certified role; autonomous shipping is a genuine but distant research horizon, not a near-term factor." },
  { id: "millwright", name: "Millwright", traits: ["R"], list: "Practical, hands-on work",
    why: "Fits practical minds — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences are the subjects that help most.",
    qual: "N1-N3 at TVET ",
    aiImpact: "Low", aiImpactNote: "hands-on installation, fault-finding and maintenance on physical plant." },
  { id: "mine-surveyor", name: "Mine Surveyor", traits: ["R", "I"], list: "Practical, hands-on, analytical work",
    why: "Fits practical minds with a analytical streak — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, English are the subjects that help most.",
    qual: "Bachelor of Mine Surveying ",
    aiImpact: "Medium", aiImpactNote: "AI is changing this field; focus on the judgement and human skills it can't replace." },
  { id: "solar-pv-installer", name: "Solar PV Installer", traits: ["R"], list: "Practical, hands-on work",
    why: "Fits practical minds — work that rewards those strengths.",
    subjects: "No fixed subject requirement — Mathematics and good language marks are a strong foundation.",
    qual: "Electrical trade route (N1-N3 + apprenticeship + trade test) ",
    aiImpact: "Low", aiImpactNote: "physical installation work, in one of the fastest-growing energy sectors in SA." },
  { id: "doctor", name: "Doctor (Medicine — MBChB)", traits: ["I", "S"], list: "Analytical, problem-solving, people-focused work",
    why: "Fits analytical minds with a people-focused streak — work that rewards those strengths.",
    subjects: "Mathematics (Pure), Maths Literacy, Physical Sciences, Life Sciences are the subjects that help most.",
    qual: "MBChB 5-6yr at one of 8 SA medical schools (UCT, Wits, Stellenbosch, UP, UKZN, UFS, SMU, Walter Sisulu).",
    aiImpact: "Low", aiImpactNote: "even in radiology, the medical specialty with the deepest current AI diagnostic tooling, the published consensus is explicitly \"augmentation, not replacement\": AI triages and flags findings, but clinical judgment, patient communication, and" },
  { id: "datasci", name: "Data Scientist / IT Specialist", traits: ["I"], list: "Find answers in data & build tech",
    why: "Strong analytical thinkers who enjoy maths and problem-solving thrive in data, software and tech roles.",
    subjects: "Mathematics is essential (NOT Maths Literacy).",
    qual: "A BSc in Computer Science / Data Science, or a National Diploma in IT at a University of Technology.",
    aiImpact: "Medium", aiImpactNote: "a genuine paradox: this is one of the *most* AI-tool-saturated careers day to day, yet WEF names AI/ML Specialists, Data Specialists, and Software Developers among the fastest-*growing* roles globally, because these are the people building " },
  { id: "scientist-researcher", name: "Scientist/Researcher (general)", traits: ["I"], list: "Analytical, problem-solving work",
    why: "Fits analytical minds — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, Life Sciences are the subjects that help most.",
    qual: "BSc 3yr ",
    aiImpact: "Medium", aiImpactNote: "AI substantially speeds up literature review, data analysis, and hypothesis generation, but original experimental design and scientific judgment remain human-directed." },
  { id: "pharmacist", name: "Pharmacist (BPharm)", traits: ["I"], list: "Analytical, problem-solving work",
    why: "Fits analytical minds — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, Life Sciences, English are the subjects that help most.",
    qual: "BPharm 4yr (Wits, UP, Rhodes, UWC, NWU, SMU — must be SAPC-approved) ",
    aiImpact: "Low", aiImpactNote: "dispensing accuracy checks and inventory are increasingly automated, but the regulated, in-person clinical/counselling role stays with a licensed pharmacist." },
  { id: "veterinarian", name: "Veterinarian (BVSc)", traits: ["I", "R"], list: "Analytical, problem-solving, practical work",
    why: "Fits analytical minds with a practical streak — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, Life Sciences, English are the subjects that help most.",
    qual: "BVSc 6yr — only offered at UP Onderstepoort, the single vet school in SA, making this arguably the most competitive programme on the entire list by scarcity of seats alone.",
    aiImpact: "Low", aiImpactNote: "hands-on physical animal care and clinical judgment, same reasoning as Doctor." },
  { id: "actuary", name: "Actuary", traits: ["I"], list: "Analytical, problem-solving work",
    why: "Fits analytical minds — work that rewards those strengths.",
    subjects: "Mathematics (Pure), English are the subjects that help most.",
    qual: "BCom/BSc/BBusSc Actuarial Science 3-4yr at one of 7 ASSA-accredited universities (UCT, Wits, Stellenbosch, UP, UJ, UFS, NWU) ",
    aiImpact: "Medium", aiImpactNote: "highly quantitative, spreadsheet/model-based work is genuinely augmented by AI tools, but the professional-exam-gated Fellow credential (ASSA) keeps sign-off judgment with licensed actuaries." },
  { id: "geologist", name: "Geologist", traits: ["I"], list: "Analytical, problem-solving work",
    why: "Fits analytical minds — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, Life Sciences are the subjects that help most.",
    qual: "BSc Geology 3yr ",
    aiImpact: "Medium", aiImpactNote: "AI increasingly assists geological data modelling and exploration analytics, but fieldwork and on-site judgment remain a core, human part of the role." },
  { id: "environmental-scientist", name: "Environmental Scientist", traits: ["I"], list: "Analytical, problem-solving work",
    why: "Fits analytical minds — work that rewards those strengths.",
    subjects: "Mathematics, Maths Literacy, Physical Sciences, Life Sciences are the subjects that help most.",
    qual: "BSc Environmental Science 3-4yr ",
    aiImpact: "Medium", aiImpactNote: "data-heavy modelling and reporting work is increasingly AI-assisted, though fieldwork and policy-facing judgment stay human." },
  { id: "biomedical-laboratory-techno", name: "Biomedical Laboratory Technologist (Medical Technology)", traits: ["I"], list: "Analytical, problem-solving work",
    why: "Fits analytical minds — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, Life Sciences, English are the subjects that help most.",
    qual: "National Diploma/BHSc-equivalent in Biomedical/Medical Laboratory Science 3-4yr (CPUT, DUT, TUT, MUT) ",
    aiImpact: "Medium", aiImpactNote: "AI increasingly assists pattern recognition in lab results (similar to radiology's trajectory), but hands-on specimen handling and quality-control judgment stay with a registered technologist." },
  { id: "software-developer", name: "Software Developer", traits: ["I"], list: "Analytical, problem-solving work",
    why: "Fits analytical minds — work that rewards those strengths.",
    subjects: "Mathematics (Pure), Physical Sciences, Information Technology are the subjects that help most.",
    qual: "BSc Computer Science or BSc/BCom IT/Informatics 3yr (widely offered) — unlike most careers on this list, a degree is not strictly legally required",
    aiImpact: "Medium", aiImpactNote: "the single most actively-reshaped career on this list day to day: the Anthropic Economic Index finds \"Computer Programmer\" the highest-coverage occupation for AI use (~75%), and routine/boilerplate coding is now substantially AI-assisted. B" },
  { id: "physicist-astronomer", name: "Physicist/Astronomer", traits: ["I"], list: "Analytical, problem-solving work",
    why: "Fits analytical minds — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences are the subjects that help most.",
    qual: "BSc Physics 3yr (Wits, UCT, UP, UKZN, Stellenbosch, UJ, Rhodes) ",
    aiImpact: "Medium", aiImpactNote: "heavy computational/data-analysis workload increasingly AI-assisted, though original research design and theoretical judgment stay human." },
  { id: "statistician", name: "Statistician", traits: ["I"], list: "Analytical, problem-solving work",
    why: "Fits analytical minds — work that rewards those strengths.",
    subjects: "Mathematics, Maths Literacy are the subjects that help most.",
    qual: "BSc/BCom Statistics/Mathematical Statistics 3yr (Wits, UP, UCT, Stellenbosch, UKZN) ",
    aiImpact: "Medium", aiImpactNote: "routine statistical analysis is increasingly AI-automatable, but interpreting results for consequential decisions (government policy, research conclusions) still needs a trained statistician's judgment." },
  { id: "dentist", name: "Dentist (BChD / BDS)", traits: ["I", "R"], list: "Analytical, problem-solving, practical work",
    why: "Fits analytical minds with a practical streak — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, Life Sciences, English are the subjects that help most.",
    qual: "BChD/BDS (5yr) ",
    aiImpact: "Low", aiImpactNote: "hands-on clinical procedures; AI assists imaging and diagnosis rather than replacing the physical work." },
  { id: "optometrist", name: "Optometrist", traits: ["I", "S"], list: "Analytical, problem-solving, people-focused work",
    why: "Fits analytical minds with a people-focused streak — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, Life Sciences, English are the subjects that help most.",
    qual: "BOptom (4yr) ",
    aiImpact: "Medium", aiImpactNote: "AI is changing this field; focus on the judgement and human skills it can't replace." },
  { id: "radiographer", name: "Radiographer (Diagnostic)", traits: ["I", "R", "S"], list: "Analytical, problem-solving, practical work",
    why: "Fits analytical minds with a practical and people-focused streak — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, Life Sciences, English are the subjects that help most.",
    qual: "Bachelor of Diagnostic Radiography (4yr) or diploma route ",
    aiImpact: "Medium", aiImpactNote: "AI image *analysis* is advancing quickly in radiology, but image acquisition, patient positioning and radiation safety stay hands-on." },
  { id: "chemical-engineer", name: "Chemical Engineer", traits: ["I", "R"], list: "Analytical, problem-solving, practical work",
    why: "Fits analytical minds with a practical streak — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, English are the subjects that help most.",
    qual: "BEng (4yr, ECSA-accredited) or BEngTech ",
    aiImpact: "Medium", aiImpactNote: "process simulation and optimisation are increasingly AI-assisted, but plant safety accountability stays with a registered engineer." },
  { id: "industrial-engineer", name: "Industrial Engineer", traits: ["I", "E", "C"], list: "Analytical, problem-solving, enterprising work",
    why: "Fits analytical minds with a enterprising and organised streak — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences are the subjects that help most.",
    qual: "BEng/BEngTech Industrial Engineering ",
    aiImpact: "Medium", aiImpactNote: "scheduling and optimisation are prime AI application areas, but systems design and change management stay human-led." },
  { id: "cybersecurity-specialist", name: "Cybersecurity Specialist", traits: ["I", "C"], list: "Analytical, problem-solving, organised work",
    why: "Fits analytical minds with a organised streak — work that rewards those strengths.",
    subjects: "Mathematics, Information Technology are the subjects that help most.",
    qual: "Genuinely multiple — (a) certificate/diploma at NQF 4-5, (b) an IT degree, (c) vendor certifications (CompTIA Security+, CEH, CISSP) usually entered *from* an existing IT role.",
    aiImpact: "Medium", aiImpactNote: "AI both automates routine threat detection and widens the attack surface; demand is growing strongly either way." },
  { id: "designer", name: "Graphic/UX Designer", traits: ["A", "I"], list: "Create visuals, brands and apps",
    why: "Creative, expressive people who like making things look good and work well are a natural fit for design.",
    subjects: "No strict requirements; Visual Arts or Design helps. Good marks in any subjects.",
    qual: "A Diploma or Degree in Graphic / Visual / UX Design at a university, UoT or design college. A strong portfolio matters most.",
    aiImpact: "Medium", aiImpactNote: "one of the more genuinely disrupted creative fields: generative image tools now handle routine layout/logo/asset work (roughly a third of surveyed businesses report this), but design strategy, brand judgment, and client work remain human-le" },
  { id: "architect", name: "Architect", traits: ["A", "I"], list: "Design buildings and spaces",
    why: "Architecture combines creativity with structure and maths - perfect for imaginative but practical thinkers.",
    subjects: "Mathematics + Physical Sciences, plus creative/visual aptitude.",
    qual: "A BAS (Architectural Studies) degree, then Honours and a Master of Architecture, or an Architectural Technology diploma.",
    aiImpact: "Low", aiImpactNote: "AI-assisted drafting/rendering tools are changing daily workflow, but the SACAP registration requirement keeps structural, safety, and legal accountability with a licensed human architect — a strong protective factor most creative careers o" },
  { id: "media", name: "Journalist/Media & Content", traits: ["E", "A"], list: "Tell stories across media",
    why: "If you love writing, ideas and communicating, media and content creation let you express and inform.",
    subjects: "Strong Languages; good marks in any subjects.",
    qual: "A Diploma or Degree in Journalism, Media Studies or Communications.",
    aiImpact: "Medium", aiImpactNote: "AI is genuinely used for data analysis, fact-checking, and generating first-draft summaries from public data, but original reporting, source relationships, and editorial verification/context stay human — the ILO frames this as transformatio" },
  { id: "musician", name: "Musician", traits: ["A"], list: "Creative, expressive work",
    why: "Fits creative minds — work that rewards those strengths.",
    subjects: "No fixed subject requirement — Mathematics and good language marks are a strong foundation.",
    qual: "Bachelor of Music 3-4yr (UCT SACM, Unisa, Wits) — audition/practical assessment typically required",
    aiImpact: "Low", aiImpactNote: "live performance and original composition remain deeply human-valued; AI-generated background/stock music is a real emerging competitor specifically for commercial/production-library work, worth a caveat, but not for performing musicians ge" },
  { id: "actor-performer", name: "Actor/Performer", traits: ["A"], list: "Creative, expressive work",
    why: "Fits creative minds — work that rewards those strengths.",
    subjects: "No fixed subject requirement — Mathematics and good language marks are a strong foundation.",
    qual: "BA Theatre and Performance 3yr (Wits: APS 34, 60% English, compulsory audition) or AFDA (NSC Bachelor's OR Diploma/Higher Certificate pass, or AFDA's own entrance exam) — audition-based entry is the norm",
    aiImpact: "Low", aiImpactNote: "in-person, audition-gated, deeply human craft; synthetic/AI performers exist as an emerging longer-term consideration for some commercial work but are not a near-term factor for the profession broadly." },
  { id: "film-tv-production", name: "Film & TV Production", traits: ["A", "E"], list: "Creative, expressive, enterprising work",
    why: "Fits creative minds with a enterprising streak — work that rewards those strengths.",
    subjects: "English is the subject that helps most.",
    qual: "AFDA Higher Certificate (1yr, lower bar) through BA (3yr)",
    aiImpact: "Medium", aiImpactNote: "AI tools are increasingly used in editing, VFX, and pre-production planning, but production management, direction, and creative judgment stay human-led." },
  { id: "interior-designer", name: "Interior Designer", traits: ["A", "C"], list: "Creative, expressive, organised work",
    why: "Fits creative minds with a organised streak — work that rewards those strengths.",
    subjects: "Mathematics, Maths Literacy, Engineering Graphics & Design, Visual Arts are the subjects that help most.",
    qual: "Diploma in Interior Design 3yr (DUT, TUT, CPUT) or BDes (Inscape)",
    aiImpact: "Medium", aiImpactNote: "AI visualisation/rendering tools are increasingly used for client presentations, but spatial judgment, client relationships, and hands-on project management stay human." },
  { id: "fashion-designer", name: "Fashion Designer", traits: ["A", "E"], list: "Creative, expressive, enterprising work",
    why: "Fits creative minds with a enterprising streak — work that rewards those strengths.",
    subjects: "Visual Arts is the subject that helps most.",
    qual: "Higher Certificate (1yr) through Diploma/BA/BCom (3yr) at LISOF, STADIO, CPUT, private colleges",
    aiImpact: "Medium", aiImpactNote: "AI increasingly assists trend forecasting and initial design concepts, but creative direction, craftsmanship, and brand identity remain human-led." },
  { id: "photographer", name: "Photographer", traits: ["A"], list: "Creative, expressive work",
    why: "Fits creative minds — work that rewards those strengths.",
    subjects: "Physical Sciences, Visual Arts are the subjects that help most.",
    qual: "Highly variable — general/freelance photography can be self-taught (no formal qualification legally needed)",
    aiImpact: "Medium", aiImpactNote: "genuinely split by specialisation: generative AI image tools are a real disruptive force for stock/commercial imagery specifically, while event, portrait, and photojournalism work requiring a real photographer's physical presence is far les" },
  { id: "animator-game-designer", name: "Animator/Game Designer", traits: ["A", "I"], list: "Creative, expressive, analytical work",
    why: "Fits creative minds with a analytical streak — work that rewards those strengths.",
    subjects: "Mathematics, Maths Literacy, Physical Sciences are the subjects that help most.",
    qual: "Split paths — Animation-focused (STADIO Bachelor of Applied Arts in 3D Animation, The Animation School Diploma) vs Game-Design-focused (Wits BA Digital Arts, Vega BCIS Game Design, Boston Higher Certificate) — portfolio…",
    aiImpact: "Medium", aiImpactNote: "AI increasingly assists routine asset generation and in-betweening in animation pipelines, but creative direction, game design judgment, and narrative craft stay human-led." },
  { id: "sound-engineer-audio-product", name: "Sound Engineer / Audio Production", traits: ["A", "R"], list: "Creative, expressive, practical work",
    why: "Fits creative minds with a practical streak — work that rewards those strengths.",
    subjects: "English is the subject that helps most.",
    qual: "Higher Certificate or Diploma in Audio Technology / Sound Engineering (Academy of Sound Engineering, Cape Audio College, SAE Institute, Oakfields, Damelin).",
    aiImpact: "Medium", aiImpactNote: "AI mixing and mastering tools are improving fast, but live sound, studio judgement and client relationships remain human." },
  { id: "hairdresser-cosmetologist", name: "Hairdresser / Cosmetologist", traits: ["A", "S", "R"], list: "Creative, expressive, people-focused work",
    why: "Fits creative minds with a people-focused and practical streak — work that rewards those strengths.",
    subjects: "No fixed subject requirement — Mathematics and good language marks are a strong foundation.",
    qual: "NQF 2-4 National Certificate at a TVET college (Level 2 ~18 months full-time) or the 3-year Occupational Certificate: Hairdressing (launched by DHET in Oct 2023) combining theory with a minimum two days per week of…",
    aiImpact: "Low", aiImpactNote: "physical, in-person personal-service work." },
  { id: "teacher", name: "Teacher", traits: ["S"], list: "Educate and shape young minds",
    why: "Patient, caring people who enjoy explaining things and helping others grow make great teachers.",
    subjects: "Languages plus the subjects you'd like to teach.",
    qual: "A 4-year BEd degree, or a Bachelor's degree followed by a PGCE. Funza Lushaka bursaries are often available.",
    aiImpact: "Low", aiImpactNote: "in-person instruction and relationship-building with learners is strongly protected; research consistently places teachers among the roles \"least in danger\" from AI, expected to use AI tools (lesson planning, marking assistance) rather than" },
  { id: "nurse", name: "Nurse", traits: ["S"], list: "Care for patients' health",
    why: "Nursing fits caring people who also enjoy health science and want hands-on impact.",
    subjects: "Life Sciences + Mathematics or Maths Literacy (varies by institution).",
    qual: "A 4-year Bachelor of Nursing, or a nursing diploma at an accredited college.",
    aiImpact: "Low", aiImpactNote: "hands-on clinical care built on human connection; allied health research explicitly identifies empathy, intuition, and person-centred care as qualities \"irreplaceable by AI,\" even as administrative/documentation tasks see AI assistance." },
  { id: "socialworker", name: "Social Worker", traits: ["S"], list: "Support people and communities",
    why: "If you want to make a real difference in people's lives, social work is deeply people-centred.",
    subjects: "Life Sciences or History helpful; good Languages.",
    qual: "A 4-year Bachelor of Social Work (BSW). Government bursaries are often available.",
    aiImpact: "Low", aiImpactNote: "deeply relational, in-person, human-judgment-intensive work; among the roles multiple sources name as least at risk." },
  { id: "psychologist", name: "Psychologist", traits: ["S", "I"], list: "Helping and caring, analytical work",
    why: "Fits people-focused minds with a analytical streak — work that rewards those strengths.",
    subjects: "Mathematics, Maths Literacy, English are the subjects that help most.",
    qual: "This is the longest, most misunderstood pathway on the list.",
    aiImpact: "Low", aiImpactNote: "the therapeutic relationship itself is the core of the work; AI chatbot mental-health tools exist as a lower-tier, supplementary self-help option, not a substitute for licensed clinical practice." },
  { id: "occupational-therapist", name: "Occupational Therapist", traits: ["S", "I"], list: "Helping and caring, analytical work",
    why: "Fits people-focused minds with a analytical streak — work that rewards those strengths.",
    subjects: "Mathematics, Maths Literacy, Physical Sciences, Life Sciences are the subjects that help most.",
    qual: "4yr Bachelor of Occupational Therapy (UCT, Wits, UP, Stellenbosch, UKZN, SMU, UWC, UFS) — min 1000 clinical hours required by HPCSA before graduation",
    aiImpact: "Low", aiImpactNote: "hands-on, person-centred care; AI increasingly assists documentation/assessment scheduling but the treatment itself stays human-delivered." },
  { id: "physiotherapist", name: "Physiotherapist", traits: ["S", "I"], list: "Helping and caring, analytical work",
    why: "Fits people-focused minds with a analytical streak — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, Life Sciences are the subjects that help most.",
    qual: "4yr Bachelor of Physiotherapy/BSc Physiotherapy (UCT, Wits, UP, Stellenbosch, UWC, SMU, UKZN) + 1yr community service",
    aiImpact: "Low", aiImpactNote: "hands-on physical treatment; among the allied-health roles research identifies as most resistant to automation." },
  { id: "speech-therapist", name: "Speech Therapist (Speech-Language Pathology)", traits: ["S", "I"], list: "Helping and caring, analytical work",
    why: "Fits people-focused minds with a analytical streak — work that rewards those strengths.",
    subjects: "Mathematics, Life Sciences, English are the subjects that help most.",
    qual: "4yr professional Bachelor's degree (a BA at some institutions despite being clinical/scientific — can surprise students) at UP, Wits, UCT, Stellenbosch, SMU.",
    aiImpact: "Low", aiImpactNote: "hands-on, relational clinical care, same reasoning as Occupational Therapist/Physiotherapist." },
  { id: "paramedic-emergency-medical-", name: "Paramedic / Emergency Medical Care", traits: ["S", "R"], list: "Helping and caring, practical work",
    why: "Fits people-focused minds with a practical streak — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, Life Sciences are the subjects that help most.",
    qual: "Genuinely tiered — (1) Higher Certificate in EMC (1yr) ",
    aiImpact: "Low", aiImpactNote: "physically-present, high-stakes emergency response requiring real-time human judgment." },
  { id: "police-officer", name: "Police Officer (SAPS)", traits: ["S", "E", "R"], list: "Helping and caring, enterprising work",
    why: "Fits people-focused minds with a enterprising and practical streak — work that rewards those strengths.",
    subjects: "English is the subject that helps most.",
    qual: "Not a degree — direct SAPS recruitment (age 18-30, SA citizen by birth, clean record, fitness/psych assessment) ",
    aiImpact: "Low", aiImpactNote: "physically-present, community-facing role requiring in-person human judgment; some analytics/case-management tools assist detective work but don't replace frontline policing." },
  { id: "hr-practitioner", name: "HR Practitioner", traits: ["S", "E"], list: "Helping and caring, enterprising work",
    why: "Fits people-focused minds with a enterprising streak — work that rewards those strengths.",
    subjects: "Mathematics, Maths Literacy, English are the subjects that help most.",
    qual: "Tiered — Higher Certificate (1yr) ",
    aiImpact: "Medium", aiImpactNote: "genuinely high AI adoption in recruiting specifically (screening, job-ad optimisation, scheduling now largely AI-assisted), but final hiring decisions and employee-relations work stay human-led — research frames this as AI eliminating ineff" },
  { id: "early-childhood-development-", name: "Early Childhood Development (ECD) Practitioner", traits: ["S"], list: "Helping and caring work",
    why: "Fits people-focused minds — work that rewards those strengths.",
    subjects: "Information Technology is the subject that helps most.",
    qual: "Genuinely tiered with a real pay/title ceiling — NQF4/5 = \"Practitioner\" (lower pay, works under supervision) vs NQF6+ Diploma = eligible to be classified/paid as \"Teacher\" in some structures.",
    aiImpact: "Low", aiImpactNote: "young children need in-person human care and supervision; deeply relational work." },
  { id: "dietician", name: "Dietician (Dietitian)", traits: ["S", "I"], list: "Helping and caring, analytical work",
    why: "Fits people-focused minds with a analytical streak — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, Life Sciences are the subjects that help most.",
    qual: "4yr BSc Dietetics (Stellenbosch, UWC, Mandela University, NWU, SMU, University of Limpopo) + 1yr community service",
    aiImpact: "Low", aiImpactNote: "clinical nutrition counselling has a strong human-relationship component; consumer meal-planning apps are a real but separate lower-tier category, not a substitute for registered clinical dietetics." },
  { id: "enrolled-nurse-auxiliary-nur", name: "Enrolled Nurse / Auxiliary Nurse", traits: ["S"], list: "Helping and caring work",
    why: "Fits people-focused minds — work that rewards those strengths.",
    subjects: "No fixed subject requirement — Mathematics and good language marks are a strong foundation.",
    qual: "Three distinct tiers — (1) 1-year Higher Certificate ",
    aiImpact: "Low", aiImpactNote: "hands-on patient care built on human presence." },
  { id: "audiologist", name: "Audiologist", traits: ["S", "I"], list: "Helping and caring, analytical work",
    why: "Fits people-focused minds with a analytical streak — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, Life Sciences, English are the subjects that help most.",
    qual: "4-year Speech-Language Pathology & Audiology degree (taught as a joint degree at most SA schools) including ~400 supervised clinical hours ",
    aiImpact: "Low", aiImpactNote: "diagnostic automation is growing, but rehabilitation and the patient relationship are central to the work." },
  { id: "firefighter", name: "Firefighter", traits: ["R", "S"], list: "Practical, hands-on, people-focused work",
    why: "Fits practical minds with a people-focused streak — work that rewards those strengths.",
    subjects: "No fixed subject requirement — Mathematics and good language marks are a strong foundation.",
    qual: "Matric + valid driver's licence + age 18+ ",
    aiImpact: "Low", aiImpactNote: "physical emergency response." },
  { id: "police-officer-correctional-", name: "Police Officer (SAPS) / Correctional Services Officer (DCS)", traits: ["S", "R", "C"], list: "Helping and caring, practical work",
    why: "Fits people-focused minds with a practical and organised streak — work that rewards those strengths.",
    subjects: "No fixed subject requirement — Mathematics and good language marks are a strong foundation.",
    qual: "Must be an SA citizen or permanent resident, aged 18-35, no criminal record or pending cases, proficient in English plus one other official language, and pass medical, psychological and fitness assessments (including…",
    aiImpact: "Low", aiImpactNote: "frontline public-safety work." },
  { id: "community-health-worker", name: "Community Health Worker", traits: ["S"], list: "Helping and caring work",
    why: "Fits people-focused minds — work that rewards those strengths.",
    subjects: "No fixed subject requirement — Mathematics and good language marks are a strong foundation.",
    qual: "NC Community Health Work NQF 2 (entry from NQF 1/ABET 4) ",
    aiImpact: "Low", aiImpactNote: "community-based, relational, in-person work." },
  { id: "entrepreneur", name: "Entrepreneur / Business Owner", traits: ["E"], list: "Build and run your own business",
    why: "Ambitious, persuasive self-starters who like leading and taking risks suit entrepreneurship.",
    subjects: "No fixed subjects; Business Studies, Accounting & Maths help.",
    qual: "No degree is required, but a BCom or business diploma builds useful skills. Many start by learning and doing.",
    aiImpact: "Low", aiImpactNote: "not really a fixed task-set to automate; entrepreneurship is defined by adapting to and exploiting new tools (including AI itself) rather than being displaced by them." },
  { id: "lawyer", name: "Lawyer", traits: ["E", "I"], list: "Advise, argue and uphold justice",
    why: "Confident, analytical people who enjoy reasoning and persuading thrive in law.",
    subjects: "Strong Languages; good marks in any subjects (Maths helps).",
    qual: "A 4-year LLB degree, then practical articles and admission as an attorney or advocate.",
    aiImpact: "Medium", aiImpactNote: "an important distinction from Paralegal (see below, not on Vula's list but the closest comparator): document review, initial legal research, and routine drafting are heavily AI-assisted, and a widely-cited Oxford study puts *paralegal/legal" },
  { id: "marketing", name: "Marketing & Sales", traits: ["E"], list: "Promote products and win customers",
    why: "Outgoing, persuasive and creative people do well in marketing, sales and brand work.",
    subjects: "Business Studies helpful; good Languages.",
    qual: "A Diploma or Degree in Marketing, Business or Communications.",
    aiImpact: "Medium", aiImpactNote: "AI now handles a substantial share of ad copywriting, social content drafting, and campaign-performance analysis, and research names \"knowledge work\" and telemarketing among the more AI-impacted task categories; but strategy, customer relat" },
  { id: "real-estate-agent", name: "Real Estate Agent", traits: ["E"], list: "Leadership and business work",
    why: "Fits enterprising minds — work that rewards those strengths.",
    subjects: "Accounting, Business Studies, Economics are the subjects that help most.",
    qual: "No degree required, but a real mandatory regulatory exam sequence: (1) register with PPRA as Candidate Property Practitioner",
    aiImpact: "Medium", aiImpactNote: "AI-driven property research, listing generation, and market analysis are increasingly standard tools (roughly a third of real-estate tasks estimated automatable), but negotiation and earning client trust are explicitly named in research as " },
  { id: "public-administration-politi", name: "Public Administration / Politics", traits: ["E"], list: "Leadership and business work",
    why: "Fits enterprising minds — work that rewards those strengths.",
    subjects: "English is the subject that helps most.",
    qual: "BA Public Administration/Governance or Bachelor of Administration 3yr (UKZN, NWU, MANCOSA, Stadio) for the civil-service track.",
    aiImpact: "Medium", aiImpactNote: "the administration-track side of this career involves genuinely automatable clerical/reporting work (see Municipal/Government Administrator below for the entry-clerk-tier detail); elected-office \"politics\" isn't a task-set that maps onto au" },
  { id: "hospitality-manager", name: "Hospitality Manager", traits: ["E"], list: "Leadership and business work",
    why: "Fits enterprising minds — work that rewards those strengths.",
    subjects: "Maths Literacy, Life Sciences, English, Geography are the subjects that help most.",
    qual: "Diploma in Hospitality Management 3yr, NQF6 (DUT, UMP) — NSC Diploma endorsement, L4 (50%+) English, L3 (40%+) Maths or L4 (50%+) Maths Lit.",
    aiImpact: "Low", aiImpactNote: "in-person guest service and operations management; hospitality is one of the sectors the Anthropic Economic Index finds least AI-exposed." },
  { id: "event-manager", name: "Event Manager", traits: ["E"], list: "Leadership and business work",
    why: "Fits enterprising minds — work that rewards those strengths.",
    subjects: "Business Studies, English, Geography are the subjects that help most.",
    qual: "Diploma/Higher Certificate in Event Management (Boston City Campus, MANCOSA, UMP — NQF5 1yr or NQF6 ~3yr).",
    aiImpact: "Medium", aiImpactNote: "AI planning/scheduling tools increasingly assist logistics coordination, but in-person execution, vendor relationships, and on-the-day problem-solving stay human." },
  { id: "insurance-broker", name: "Insurance Broker", traits: ["E"], list: "Leadership and business work",
    why: "Fits enterprising minds — work that rewards those strengths.",
    subjects: "Mathematics, Accounting, Business Studies, Economics are the subjects that help most.",
    qual: "Short route — Higher Certificate in Short-Term Insurance/Risk Management (NQF5, ~1yr)",
    aiImpact: "Medium", aiImpactNote: "claims processing, policy checking, and risk calculation are described in research as \"ideal for AI,\" genuinely shifting day-to-day work, but complex claims and client relationship-building stay with the human broker; FSCA-regulated advice " },
  { id: "import-export-trader", name: "Import/Export Trader", traits: ["E"], list: "Leadership and business work",
    why: "Fits enterprising minds — work that rewards those strengths.",
    subjects: "Maths Literacy, Business Studies, Economics are the subjects that help most.",
    qual: "No mandatory degree.",
    aiImpact: "Medium", aiImpactNote: "customs documentation, compliance checking, and logistics coordination are increasingly automatable, but cross-border deal-making and supplier/buyer relationships stay human-led." },
  { id: "tour-operator", name: "Tour Operator", traits: ["E"], list: "Leadership and business work",
    why: "Fits enterprising minds — work that rewards those strengths.",
    subjects: "English, Geography, History are the subjects that help most.",
    qual: "No degree required — flexible.",
    aiImpact: "Medium", aiImpactNote: "AI travel-planning tools increasingly compete with human operators for routine itinerary-building specifically, though this career's own noted Operator-vs-Guide split matters here too: the in-person Tourist Guide side of tourism work is muc" },
  { id: "financial-advisor", name: "Financial Advisor", traits: ["E", "C", "S"], list: "Leadership and business, organised work",
    why: "Fits enterprising minds with a organised and people-focused streak — work that rewards those strengths.",
    subjects: "Mathematics is the subject that helps most.",
    qual: "Appointed as a representative at a licensed FSP ",
    aiImpact: "Medium", aiImpactNote: "robo-advice and automated portfolio tools are growing, but regulated advice and client trust stay human-accountable." },
  { id: "accountant", name: "Accountant / Chartered Accountant", traits: ["C"], list: "Manage money, audits and finances",
    why: "Organised, detail-focused people who are good with numbers are well suited to accounting and finance.",
    subjects: "Mathematics (essential) + Accounting.",
    qual: "A BCom Accounting degree, then SAICA articles to qualify as a Chartered Accountant (CA).",
    aiImpact: "Medium", aiImpactNote: "genuinely lower exposure than the \"Conventional\" stereotype suggests: labour projections show accountants/auditors growing even as bookkeeping clerks decline, because AI automates routine entry-level tasks while judgment-based work (substan" },
  { id: "banker", name: "Banking & Finance", traits: ["C"], list: "Work with money, markets and clients",
    why: "If you like numbers, structure and business, finance offers stable and varied careers.",
    subjects: "Mathematics + Accounting helpful.",
    qual: "A BCom in Finance/Economics, or a finance diploma at a UoT/college.",
    aiImpact: "Medium", aiImpactNote: "Entry-level teller and routine-processing roles are shrinking fastest — the advisory and investment side of banking is far more secure, so aim to build toward that." },
  { id: "logistics", name: "Logistics & Supply Chain", traits: ["C"], list: "Move goods and plan operations",
    why: "Organised planners who like efficiency and coordination suit logistics and operations.",
    subjects: "Mathematics or Maths Literacy; Business Studies helpful.",
    qual: "A Diploma or Degree in Logistics, Supply Chain or Operations Management.",
    aiImpact: "Medium", aiImpactNote: "route optimisation, demand forecasting, and inventory management are increasingly AI/algorithm-driven (\"agentic AI\" tools are a real, fast-growing category here), but physical coordination and exception-handling when things go wrong stay hu" },
  { id: "bookkeeper", name: "Bookkeeper", traits: ["C"], list: "Organised, detail-focused work",
    why: "Fits organised minds — work that rewards those strengths.",
    subjects: "Mathematics is the subject that helps most.",
    qual: "ICB (Institute of Certified Bookkeepers) is the realistic route and notably does NOT require matric for entry levels — National Certificate (Grade 10+, age 16+) ",
    aiImpact: "High", aiImpactNote: "this is the clearest, most robustly-sourced High rating on the whole list: the Oxford Frey/Osborne study puts \"Bookkeeping, Accounting, and Auditing Clerks\" at 98% computerisation probability, and current labour projections separately show " },
  { id: "payroll-administrator", name: "Payroll Administrator", traits: ["C"], list: "Organised, detail-focused work",
    why: "Fits organised minds — work that rewards those strengths.",
    subjects: "No fixed subject requirement — Mathematics and good language marks are a strong foundation.",
    qual: "Matric + Certificate/Diploma in Payroll Administration (NQF4-5, SETA-accredited providers) is the realistic entry path",
    aiImpact: "High", aiImpactNote: "routine, rule-based, structured payroll processing matches the exact profile WEF's \"fastest-declining\" clerical/data-entry category describes; payroll software already automates most calculation and compliance-checking work. Progression tow" },
  { id: "municipal-government-adminis", name: "Municipal/Government Administrator", traits: ["C"], list: "Organised, detail-focused work",
    why: "Fits organised minds — work that rewards those strengths.",
    subjects: "Mathematics, Maths Literacy are the subjects that help most.",
    qual: "Spans entry clerk (matric only) through Municipal Manager (degree + 5+yr senior experience) — Diploma or BA/BCom/BAdmin in Public Administration (UNISA, MANCOSA, Mandela University) needed for progression toward…",
    aiImpact: "Medium", aiImpactNote: "AI is changing this field; focus on the judgement and human skills it can't replace." },
  { id: "court-clerk", name: "Court Clerk", traits: ["C"], list: "Organised, detail-focused work",
    why: "Fits organised minds — work that rewards those strengths.",
    subjects: "No fixed subject requirement — Mathematics and good language marks are a strong foundation.",
    qual: "Matric (Grade 12) is the minimum and often sufficient — current OCJ postings explicitly state \"no previous work experience required.\" A 3yr law-related diploma/degree (NQF6) is advantageous, not mandatory, for entry…",
    aiImpact: "High", aiImpactNote: "squarely routine, structured administrative/document-processing work, directly matching WEF's fastest-declining clerical category. Progression toward Registrar or paralegal/LLB study (already noted in this entry's own Pathway) is a meaningf" },
  { id: "librarian", name: "Librarian", traits: ["C"], list: "Organised, detail-focused work",
    why: "Fits organised minds — work that rewards those strengths.",
    subjects: "Mathematics, English are the subjects that help most.",
    qual: "Diploma or Bachelor's in Library and Information Science (UCT, DUT, UNISA Postgraduate Diploma) is the standard professional route",
    aiImpact: "Medium", aiImpactNote: "AI-powered search/discovery tools increasingly handle routine information retrieval and cataloguing (pushing the paraprofessional Library Assistant tier toward higher exposure), but research assistance, curation, and community/education pro" },
  { id: "quantity-surveyor", name: "Quantity Surveyor", traits: ["C", "R"], list: "Organised, detail-focused, practical work",
    why: "Fits organised minds with a practical streak — work that rewards those strengths.",
    subjects: "Mathematics, Physical Sciences, English are the subjects that help most.",
    qual: "BSc/BTech Quantity Surveying (SACQSP-accredited: UP, UCT, CUT, Wits) ",
    aiImpact: "Medium", aiImpactNote: "cost estimation and quantity takeoff software has already been substantially digitised for decades, with generative AI adding a further layer of automation to routine measurement work, but the SACQSP-registered professional's contractual/le" },
  { id: "tax-practitioner", name: "Tax Practitioner", traits: ["C", "I"], list: "Organised, detail-focused, analytical work",
    why: "Fits organised minds with a analytical streak — work that rewards those strengths.",
    subjects: "Mathematics, Accounting are the subjects that help most.",
    qual: "Tiered by qualification and experience — NQF 6 (including at least one accounting and one tax module) + 1 year tax experience",
    aiImpact: "Medium", aiImpactNote: "routine return preparation is heavily automated, but advisory work, structuring and representation before SARS remain professional acts." },
];

const careerById = (id) => CAREERS.find((c) => c.id === id);

module.exports = { TRAIT_NAMES, CAREERS, careerById };
