// STRUCTURED SUBJECT REQUIREMENTS — counsellor-reviewed final (July 2026).
//
// Powers the WhatsApp "what could I study based on my subjects?" and "I already
// know what I want to study" paths. Keyed by the same career id as lib/careers.js.
//
// This data has been reviewed and confirmed by a career counsellor against the
// 100-career master review. All 100 careers are now keyed here. Entries with
// needs_review:false are cleared for learner-facing "you qualify / here's what it
// takes" use. Eight entries remain needs_review:true — flagged "verify with
// institution" in the source review and must carry a "confirm with the
// institution" caveat until re-confirmed.
//
// NSC levels: L2=30-39%, L3=40-49%, L4=50-59%, L5=60-69%, L6=70-79%, L7=80-100%.
// "recommended" subjects are NOT encoded as hard gates in `required` (that would
// falsely exclude learners); they live in `source_text`. See docs/SUBJECT_REQUIREMENTS_SPEC.md.

const SUBJECT_REQUIREMENTS = {
  "actor-performer": { maths: "no_maths_gate", required: [], no_firm_requirement: true, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. Dramatic Arts recommended, not required. Entry: open — audition is the primary gatekeeper." },
  "agricultural-farm-manager": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":4},{"subject":"English","min_level":4},{"subject":"Physical/Life/Agricultural Sciences","min_level":3}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 (50%). English L4; at least L3 in Physical Sciences OR Life Sciences OR Agricultural Sciences. Diploma/Degree entry." },
  "audiologist": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":3},{"subject":"English","min_level":4},{"subject":"Life Orientation","min_level":4},{"subject":"Life or Physical Sciences","min_level":3}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L3 (40%). English L4, Life Orientation L4, Life Sciences OR Physical Sciences L3. Minimum 30 APS (excl. LO)." },
  "banker": { maths: "either_accepted", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L3 (40%) preferred / Maths Literacy accepted at L6 (70%). Economics, Accounting, Physical Sciences recommended. BCom / bridging route." },
  "biomedical-laboratory-techno": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":3},{"subject":"English","min_level":3},{"subject":"Physical Sciences","min_level":3},{"subject":"Life Sciences","min_level":3}], no_firm_requirement: false, needs_review: true, confidence: "Counsellor-reviewed — flagged to verify with institution",
    source_text: "Maths: Pure L3 (40%). English L3, Physical Sciences L3, Life Sciences L3. Diploma/Degree entry. VERIFY against a specific institution." },
  "boilermaker": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none required (Pure recommended). Physical Sciences, EGD, Mechanical Tech recommended. Trade / TVET N2 route — open entry." },
  "bookkeeper": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none required (Pure recommended). No mandatory subjects. Open entry." },
  "bricklayer": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none for base entry (Tech/Pure L3 for the trade track). Technical/Physical Sciences recommended. Grade 9 minimum / open entry." },
  "carpenter-joiner": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none required (Pure recommended). No mandatory subjects. Open entry (Grade 9+ / TVET path)." },
  "chemical-engineer": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":5},{"subject":"English","min_level":4},{"subject":"Physical Sciences","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L5 (60%). English L4 (50%), Physical Sciences L5 (60%). Minimum APS 30." },
  "community-health-worker": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. No subject gate. Open entry (Grade 10 minimum in practice)." },
  "court-clerk": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. No specific subjects. Open entry (Matric / NSC pass)." },
  "cybersecurity-specialist": { maths: "either_accepted", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none for certificate routes; Pure L4+ for degree routes. IT / CAT recommended. Open entry for certs; degree gates vary." },
  "dentist": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":5},{"subject":"English","min_level":5},{"subject":"Physical and/or Life Sciences","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L5 (60%). English L5, Physical Sciences and/or Life Sciences L5. Competitive composite-index selection." },
  "dietician": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":4},{"subject":"Physical Sciences","min_level":4},{"subject":"Life Sciences","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 (50%). Physical Sciences L4 (50%), Life Sciences L4 (50%). NSC aggregate 60%+." },
  "early-childhood-development-": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. No subject gate. Open entry (Grade 9/10 for NQF4; NSC for Diploma)." },
  "electrician": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure recommended / none required. Physical Sciences recommended. Open entry (N2/NCV TVET pathway)." },
  "enrolled-nurse-auxiliary-nur": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none (Maths Literacy accepted). Life Sciences recommended. Open entry (Grade 12 for Higher Cert/Diploma)." },
  "entrepreneur": { maths: "either_accepted", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: either accepted (Pure keeps BCom open). Business Studies, Economics, Accounting recommended. Open entry." },
  "fashion-designer": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. Visual Arts/Design recommended, not required. Open entry (Matric + portfolio/interview)." },
  "film-tv-production": { maths: "no_maths_gate", required: [{"subject":"English","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. English L4 (50%). Open entry / NSC Bachelor's pass (APS 20-24)." },
  "financial-advisor": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none (either recommended). No mandatory subjects. Open entry (Matric pass)." },
  "firefighter": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. No subject gate. Open entry (Matric pass + physical fitness)." },
  "fitter-turner": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none (Pure/Tech L3 advantageous for N2). Physical Sciences recommended. Open entry (Grade 9 minimum)." },
  "game-ranger-wildlife-manager": { maths: "either_accepted", required: [{"subject":"Life Sciences","min_level":3},{"subject":"Geography","min_level":3}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Literacy accepted for FGASA; Pure L4 for BSc. Life Sciences L3+, Geography L3+. Track dependent (FGASA open; BSc needs endorsement)." },
  "geologist": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":5},{"subject":"Physical Sciences","min_level":5},{"subject":"Life Sciences","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L5 (60%). Physical Sciences L5 (60%), Life Sciences L4/L5. BSc degree entry." },
  "hairdresser-cosmetologist": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. No subject gate. Open entry (Grade 9 minimum)." },
  "hospitality-manager": { maths: "either_accepted", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: either accepted. Hospitality Studies, Tourism, Life Sciences recommended. Open entry (Diploma/Degree entry)." },
  "import-export-trader": { maths: "either_accepted", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: either accepted. Business Studies, Economics, Foreign Language recommended. Open entry." },
  "industrial-engineer": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":5},{"subject":"Physical Sciences","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L5 (60%). Physical Sciences L5 (60%). BEng / BSc Eng degree entry." },
  "insurance-broker": { maths: "either_accepted", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: either accepted. Accounting, Business Studies, Economics recommended. Open entry (Matric + RE exams post-matric)." },
  "media": { maths: "no_maths_gate", required: [{"subject":"English","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. English L5 (60%). Open entry — English proficiency is the gatekeeper." },
  "librarian": { maths: "either_accepted", required: [{"subject":"English","min_level":3}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: either accepted at L3. English L3 (40%); Languages/CAT recommended. NSC Diploma / Degree pass." },
  "logistics": { maths: "either_accepted", required: [{"subject":"English","min_level":3}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L3 preferred / Maths Literacy accepted L4 for diplomas. English L3 (40%); Accounting recommended. Diploma/Degree entry." },
  "marketing": { maths: "either_accepted", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Maths Literacy accepted / either. Business Studies, Economics recommended. Open entry." },
  "millwright": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none (Pure/Tech recommended). Physical Sciences recommended. Open entry (Grade 9 minimum; N2 trade path)." },
  "mine-surveyor": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":5},{"subject":"English","min_level":4},{"subject":"Physical or Technical Science","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L5 (60%) OR Technical Maths L5 (60%). English L4 (50%), Physical Sciences OR Technical Science L5. Minimum APS 23." },
  "municipal-government-adminis": { maths: "either_accepted", required: [{"subject":"Language of Instruction","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L3 / Maths Literacy accepted L6. Language of Instruction L4 (50%). Open entry (Matric pass / admin clerk jobs)." },
  "musician": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. NSC Music OR Unisa Gr5 / ABRSM Gr6 theory. Open entry (audition / theory certification)." },
  "occupational-therapist": { maths: "either_accepted", required: [{"subject":"English","min_level":4},{"subject":"Physical or Life Sciences","min_level":4}], no_firm_requirement: false, needs_review: true, confidence: "Counsellor-reviewed — flagged to verify with institution",
    source_text: "Maths: Pure L4 / Maths Literacy accepted L5 (institution dependent). English L4 (50%), Physical Sciences OR/AND Life Sciences L4. Degree entry (APS ~30+). VERIFY." },
  "optometrist": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":4},{"subject":"English","min_level":4},{"subject":"Physical Sciences","min_level":4},{"subject":"Life Sciences","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4+ (50%+). English L4+, Physical Sciences L4+, Life Sciences L4+. Minimum APS 26-30+." },
  "paramedic-emergency-medical-": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":3},{"subject":"Life Sciences","min_level":3},{"subject":"Physical Sciences","min_level":3}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L3 (40%). Life Sciences L3, Physical Sciences L3. APS 24-26 + fitness/swimming." },
  "payroll-administrator": { maths: "either_accepted", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: either (Pure/Lit) recommended. No mandatory subjects. Open entry (Matric pass)." },
  "pharmacist": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":4},{"subject":"English","min_level":4},{"subject":"Physical Sciences","min_level":4},{"subject":"Life Sciences","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 (50% floor, L5 typical). English L4, Physical Sciences L4, Life Sciences L4. BPharm degree entry." },
  "photographer": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. Visual Arts, Design, Physical Sciences recommended. Open entry." },
  "physicist-astronomer": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":6},{"subject":"Physical Sciences","min_level":5}], no_firm_requirement: false, needs_review: true, confidence: "Counsellor-reviewed — flagged to verify with institution",
    source_text: "Maths: Pure L6 (70%, estimated proxy). Physical Sciences L5 (60%, estimated proxy). BSc degree entry. VERIFY." },
  "physiotherapist": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":5},{"subject":"Physical Sciences","min_level":4},{"subject":"Life Sciences","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L5 (60%). Physical Sciences L4 (50%), Life Sciences L4 (50%). Competitive degree entry (aggregate 60%+)." },
  "plumber": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none (Pure recommended). Physical Sciences recommended. Open entry (Grade 9 / N2 TVET trade route)." },
  "police-officer": { maths: "no_maths_gate", required: [{"subject":"English","min_level":null}], no_firm_requirement: true, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. English (pass). Open entry (Matric pass + language fluency)." },
  "police-officer-correctional-": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. No specific subjects. Open entry (Matric pass)." },
  "public-administration-politi": { maths: "either_accepted", required: [{"subject":"English","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: either accepted. English L4 (40-50%). Open entry (NSC Diploma / Bachelor's pass)." },
  "radiographer": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":4},{"subject":"English","min_level":5},{"subject":"Physical Sciences","min_level":4},{"subject":"Life Sciences","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 (50%). English L5 (60%), Physical Sciences L4 (50%), Life Sciences L5 (60%). Minimum APS 31." },
  "refrigeration-technician": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none (Pure/Tech recommended). Physical Sciences recommended. Open entry (Grade 9 minimum)." },
  "scientist-researcher": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":5},{"subject":"Physical or Life Sciences","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L5 (60%). Physical Sciences OR Life Sciences L5 (track dependent). BSc degree entry." },
  "solar-pv-installer": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. No subject gate. Open entry (assumes NQF4 numeracy / electrician status)." },
  "sound-engineer-audio-product": { maths: "no_maths_gate", required: [{"subject":"English","min_level":null}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. English pass (~33%+). Open entry (Grade 10/12 depending on provider)." },
  "speech-therapist": { maths: "either_accepted", required: [{"subject":"English","min_level":5},{"subject":"Life Sciences","min_level":5}], no_firm_requirement: false, needs_review: true, confidence: "Counsellor-reviewed — flagged to verify with institution",
    source_text: "Maths: Pure L4 / Maths Literacy accepted (institution dependent). English L5 (60%), Life Sciences L5 (60%). Minimum APS 32-34. VERIFY." },
  "statistician": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":5},{"subject":"English","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L5 (BCom) to L6 (BSc). English L4 (50%). Minimum APS 32-34." },
  "tax-practitioner": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none (either recommended). Accounting recommended. Open entry (Matric pass)." },
  "teacher": { maths: "either_accepted", required: [{"subject":"English","min_level":4},{"subject":"2 Priority Teaching Subjects","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Maths Literacy L4 for Gr R-3; Pure L4 for teaching high-school Maths. English L4 (50%), 2 priority teaching subjects L4. NSC Bachelor's pass." },
  "tour-operator": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. Tourism, Geography, History recommended. Open entry." },
  "veterinarian": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":5},{"subject":"English","min_level":5},{"subject":"Physical Sciences","min_level":5},{"subject":"Life Sciences","min_level":5}], no_firm_requirement: false, needs_review: true, confidence: "Counsellor-reviewed — flagged to verify with institution",
    source_text: "Maths: Pure L5 (60%, inferred). English L5, Physical Sciences L5, Life Sciences L5. BVSc degree entry. VERIFY." },
  "welder": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none (Pure/Tech recommended). Physical/Civil/Mechanical Tech recommended. Open entry (Grade 9 minimum)." },
  "accountant": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L5 (60%). English recommended, Accounting optional. Degree entry." },
  "actuary": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":7},{"subject":"English","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L7 (80%+). English L5+ (60%+). Matric average 80-85%." },
  "animator-game-designer": { maths: "either_accepted", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L3 / Maths Literacy L5 / none for digital arts. Physical Sciences / IT recommended. Portfolio + motivation letter." },
  "architect": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":4},{"subject":"English","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 (50%). English L4 (50%), EGD/Physical Science recommended. Degree entry + portfolio." },
  "chef": { maths: "either_accepted", required: [{"subject":"English","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Maths Literacy accepted L4 (50%) OR Pure L3 (40%). English L4 (50%). Certificate / Diploma entry." },
  "commercial-pilot": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure recommended / none strictly required. Physical Sciences recommended. Full NSC + Class 1 Medical." },
  "datasci": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L5+ (60%+). Physical Sciences, IT/CAT recommended. Degree entry." },
  "diesel-mechanic": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":4},{"subject":"Physical Sciences","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 (50%) OR Technical Maths L4. Physical Sciences L4 (50%). TVET entry + valid driver's licence." },
  "doctor": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":5},{"subject":"English","min_level":5},{"subject":"Physical Sciences","min_level":5},{"subject":"Life Sciences","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L5 (60%). English L5, Physical Sciences L5, Life Sciences L5 (institution dependent). Highly competitive selection / NBT." },
  "engineer": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":5},{"subject":"English","min_level":4},{"subject":"Physical Sciences","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L5 (60%). English L4 (50%), Physical Sciences L5 (60%). BEng / BSc Eng degree entry." },
  "environmental-scientist": { maths: "either_accepted", required: [{"subject":"English","min_level":4},{"subject":"Geography","min_level":4},{"subject":"Life or Physical Sciences","min_level":4}], no_firm_requirement: false, needs_review: true, confidence: "Counsellor-reviewed — flagged to verify with institution",
    source_text: "Maths: Pure L4 / Maths Literacy L6 (institution dependent). English L4, Geography L4, Life Sciences OR Physical Sciences L4. Degree entry. VERIFY." },
  "event-manager": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. Business Studies, Tourism recommended. Open entry." },
  "designer": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. Visual Arts, Design, CAT/IT recommended. Open entry / portfolio." },
  "hr-practitioner": { maths: "either_accepted", required: [{"subject":"English","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Maths Literacy accepted L5 (60%) OR Pure L4 (50%). English L4 (50%). Diploma / Degree entry." },
  "interior-designer": { maths: "either_accepted", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Maths Literacy accepted L5 (60%) OR Pure L3 (40%). Visual Arts / Design / EGD recommended. Portfolio + interview + test." },
  "landscaper-landscape-technic": { maths: "either_accepted", required: [{"subject":"English","min_level":3}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: either — combined Maths + Science level rule ((Maths + Life/Physical Sci level) >= 7). English L3. Diploma entry." },
  "lawyer": { maths: "either_accepted", required: [{"subject":"English","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 / Maths Literacy accepted L5. English L5 (60% HL / 70% FAL). Minimum APS 31-32." },
  "merchant-navy-marine-officer": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":4},{"subject":"Physical Sciences","min_level":4}], no_firm_requirement: false, needs_review: true, confidence: "Counsellor-reviewed — flagged to verify with institution",
    source_text: "Maths: Pure L4. Physical Sciences L4. SAMSA / Maritime Institute entry. VERIFY." },
  "mechanic": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":4},{"subject":"Physical Sciences","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 (50%, recommended). Physical Sciences L4 (50%, recommended). Open entry / N2 TVET trade route." },
  "nurse": { maths: "either_accepted", required: [{"subject":"English","min_level":4},{"subject":"Life Sciences","min_level":4}], no_firm_requirement: false, needs_review: true, confidence: "Counsellor-reviewed — flagged to verify with institution",
    source_text: "Maths: Pure L4 / Maths Literacy L5 (institution dependent). English L4 (50%), Life Sciences L4 (50%). Nursing College / University entry. VERIFY." },
  "psychologist": { maths: "either_accepted", required: [{"subject":"English","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L5 / Maths Literacy accepted L5. English L5 (60%). BA / BPsych degree entry." },
  "quantity-surveyor": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":5},{"subject":"English","min_level":5},{"subject":"Physical Sciences","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L5 (60%). English L5 (60%), Physical Sciences L4 (50%). Minimum APS 30." },
  "real-estate-agent": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. Economics, Business Studies, Accounting recommended. Open entry (FETC Real Estate / PPRA)." },
  "socialworker": { maths: "either_accepted", required: [{"subject":"English","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L2 / Maths Literacy accepted L3. English L4 (50%). BSW degree entry." },
  "software-developer": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4+. Physical Sciences, IT/CAT recommended. Diploma / Degree entry." },
  "data-analyst": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 (50%). CAT/IT/Accounting recommended. BCom/BSc degree or diploma." },
  "cloud-network-engineer": { maths: "either_accepted", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 (degree) / Maths Literacy accepted L4 (cert). IT/CAT recommended. Vendor certs or diploma/degree." },
  "biokineticist": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":4},{"subject":"Life Sciences","min_level":4},{"subject":"Physical Sciences","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 (50%). Life Sciences L4 (50%), Physical Sciences L4. BSc Human Movement Science." },
  "dental-therapist": { maths: "either_accepted", required: [{"subject":"English","min_level":4},{"subject":"Life Sciences","min_level":4},{"subject":"Physical Sciences","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 or Maths Literacy accepted L5. English L4, Life Sciences L4, Physical Sciences L4. B Health Sciences degree." },
  "sonographer": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":4},{"subject":"English","min_level":5},{"subject":"Physical Sciences","min_level":4},{"subject":"Life Sciences","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 (50%). English L5, Physical Sciences L4, Life Sciences L5. B Health Sciences (Ultrasound)." },
  "compliance-officer": { maths: "either_accepted", required: [{"subject":"English","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L3 / Maths Literacy accepted L5. English L4, Accounting/Economics recommended. BCom / LLB / Higher Cert." },
  "paralegal": { maths: "either_accepted", required: [{"subject":"English","min_level":5}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L3 / Maths Literacy accepted L4. English L5 (60%+). Higher Certificate / Diploma." },
  "instrumentation-technician": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":4},{"subject":"Physical or Technical Science","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 or Technical Maths L4. Physical Sciences L4 or Technical Science L4. TVET N2-N3 / National Diploma." },
  "sheq-officer": { maths: "either_accepted", required: [{"subject":"English","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L3 / Maths Literacy accepted L4. English L4, Life/Physical Sciences helpful. Open entry (SAMTRAC / Health Cert)." },
  "rigging-crane-operator": { maths: "no_maths_gate", required: [], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: none. No subject gate. Open entry (Grade 10/12 + fitness) + rigging/crane certification." },
  "environmental-health-practitioner": { maths: "pure_required", required: [{"subject":"Mathematics (Pure)","min_level":4},{"subject":"English","min_level":4},{"subject":"Life Sciences","min_level":4},{"subject":"Physical Sciences","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 (50%). English L4, Life Sciences L4, Physical Sciences L4. BHSc Environmental Health." },
  "horticulturist-agronomist": { maths: "either_accepted", required: [{"subject":"Life or Agricultural Sciences","min_level":4}], no_firm_requirement: false, needs_review: false, confidence: "Counsellor-reviewed (final)",
    source_text: "Maths: Pure L4 (BSc) / Maths Literacy accepted L5 (Diploma). Life Sciences OR Agricultural Sciences L4. Diploma / BSc Agriculture." }
};

module.exports = { SUBJECT_REQUIREMENTS };
